CREATE TABLE "User" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    hashedRefreshToken VARCHAR(255),
    role VARCHAR(20) DEFAULT 'USER' NOT NULL
);

CREATE TABLE "Category" (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    img VARCHAR(255)
);

CREATE TABLE "Post" (
    id SERIAL PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT NOW(),
    slug VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    "desc" TEXT NOT NULL,
    img VARCHAR(255),
    views INT DEFAULT 0,
    catSlug VARCHAR(255) NOT NULL,
    userEmail VARCHAR(255) NOT NULL,
    CONSTRAINT fk_category FOREIGN KEY (catSlug) REFERENCES "Category"(slug) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_user FOREIGN KEY (userEmail) REFERENCES "User"(email) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "Comment" (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT NOW(),
    user_id INT NOT NULL,
    post_id INT NOT NULL,
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES "User"(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES "Post"(id) ON DELETE NO ACTION ON UPDATE NO ACTION
);